# Site settings
title: "Amresh Kumar"
description: "Seeking a challenging opportunity as a System Administrator with a growth oriented organization where I can utilize my creativity and breadth of technical skills to contribute to their success and my own."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Amresh Kumar"
resume_title:                   "Red Hat Certified System Administrator"
resume_contact_email:           "amresh.aaa@gmail.com"
resume_contact_telephone:       "8109958260"
resume_contact_address:         "401, C-Block, Nisarg Dream, Next to Kaveri Pratham, Ambli-Shilaj Flyover, Sardar Patel Ring Road, Bopal, Ahmedabad, Gujarat 380058"
resume_header_contact_info: "401, C-Block, Nisarg Dream, Next to Kaveri Pratham, Ambli-Shilaj Flyover, Sardar Patel Ring Road, Bopal, Ahmedabad, Gujarat 380058 | 8109958260 | amresh.aaa@gmail.com"
resume_header_intro: "<p>Seeking a challenging opportunity as a System Administrator with a growth oriented organization where I can utilize my creativity and breadth of technical skills to contribute to their success and my own.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/AmreshPrajapati/amreshprajapati.github.io/"
  #resume_twitter_url:           "http://twitter.com/jglovier"
#  resume_dribbble_url:          "https://dribbble.com/jag"
   resume_facebook_url:          "https://www.facebook.com/AAAmresh1"
  resume_linkedin_url:          "https://www.linkedin.com/in/amresh-kumar-188a9619/"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://amreshprajapati.github.io/"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
